### ISSUE TITLE
Problem at startup

### ISSUE THREAD

**Issue by SrMast3r** [EvilKingdom/DiscordRankSync#1]
When starting the bot, this problem occurs

Paper 1.12.2
Java 18

[01:30:36 INFO]: [DiscordRankSync] Logged into discord bot
[01:30:36 ERROR]: Error occurred while enabling DiscordRankSync v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Guild.upsertCommand(net.dv8tion.jda.api.interactions.commands.build.CommandData)" because the return value of "net.dv8tion.jda.api.JDA.getGuildById(String)" is null        at net.evilkingdom.discordranksync.DiscordRankSync.loadSlashCommands(DiscordRankSync.java:103) ~[?:?]
        at net.evilkingdom.discordranksync.DiscordRankSync.loadAll(DiscordRankSync.java:65) ~[?:?]
        at net.evilkingdom.discordranksync.DiscordRankSync.onEnable(DiscordRankSync.java:55) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:311) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:450) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:411) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:349) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:638) ~[patched_1.12.2.jar:git-Reaper-"2d0a5dc"]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by TheTrustyPwo** [comment]
Sorry, I can't really help as I've not touched this codebase in a really long time. But have you tried running it on 1.17? Or perhaps the guild ID you have inputted in invalid?

**Comment by benxh7** [comment]
It's weird because the same thing happened to me, but I doubt it's the Guild ID because it doesn't generate the config.yml file to modify that, maybe it's an incompatibility between versions, if you can fix that I would be very grateful.
